"""Generate docs/EVIDENCE_M1.md — the M1.1 evidence pack (SPEC_M2 P0.d).

Run after a corpus build: reads the pinned snapshot, data/v1/*.parquet and
data/quarantine/quarantine.csv. Deterministic output.
"""

import csv
import json
import sys
from collections import Counter
from pathlib import Path

import polars as pl

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from cricstate.download import DATA_DIR, snapshot_dir

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "docs" / "EVIDENCE_M1.md"


def main() -> None:
    snap = snapshot_dir() / "json"
    files = sorted(snap.glob("*.json"))

    # (1) data_version histogram + per-file competition lookup (one pass)
    versions: Counter[str] = Counter()
    competition: dict[str, str] = {}
    for f in files:
        with open(f) as fh:
            raw = json.load(fh)
        versions[str(raw.get("meta", {}).get("data_version"))] += 1
        event = raw.get("info", {}).get("event")
        name = event.get("name") if isinstance(event, dict) else None
        competition[f.stem] = str(name) if name else "(no event)"

    # (2) quarantine reason x competition
    with open(DATA_DIR / "quarantine" / "quarantine.csv") as fh:
        quarantines = list(csv.DictReader(fh))
    reason_hist = Counter(q["reason"] for q in quarantines)
    in_scope_reasons = [q for q in quarantines if q["reason"] != "E_FORMAT_OOS"]
    comp_hist = Counter(competition.get(q["match_id"], "?") for q in in_scope_reasons)
    cross: Counter[tuple[str, str]] = Counter(
        (q["reason"], competition.get(q["match_id"], "?")) for q in in_scope_reasons
    )
    ball_acc = [q for q in quarantines if q["reason"] == "E_BALL_ACCOUNTING"][:3]

    deliveries = pl.read_parquet(DATA_DIR / "v1" / "deliveries.parquet")
    matches = pl.read_parquet(DATA_DIR / "v1" / "matches.parquet")

    # (3) outcome alphabet with train frequencies
    train = deliveries.filter(pl.col("temporal_split") == "train")
    alpha = (
        train.group_by("outcome_class")
        .len()
        .with_columns((pl.col("len") / train.height).alias("freq"))
        .sort("len", descending=True)
    )

    # (4) split boundaries + counts
    split_counts = deliveries.group_by("temporal_split").len().sort("temporal_split").to_dicts()
    match_counts = matches.group_by("temporal_split").len().sort("temporal_split").to_dicts()
    bounds = (
        matches.group_by("temporal_split")
        .agg(pl.col("start_date").min().alias("min"), pl.col("start_date").max().alias("max"))
        .sort("min")
        .to_dicts()
    )

    lines = [
        "# EVIDENCE PACK — M1.1 corpus",
        "",
        "Generated by `scripts/evidence_m1.py` against `data/MANIFEST` snapshot.",
        "",
        "## (1) data_version histogram (all snapshot files)",
        "",
        "| data_version | files |",
        "|---|---|",
        *(f"| {v} | {n} |" for v, n in sorted(versions.items())),
        "",
        "## (2) Quarantine",
        "",
        "### Reason histogram (all files)",
        "",
        "| reason | count |",
        "|---|---|",
        *(f"| {r} | {n} |" for r, n in sorted(reason_hist.items())),
        "",
        "### In-scope quarantines by reason x competition (top 10 competitions)",
        "",
        "| competition | " + " | ".join(sorted({r for r, _ in cross})) + " | total |",
        "|---|" + "---|" * (len({r for r, _ in cross}) + 1),
    ]
    reasons_sorted = sorted({r for r, _ in cross})
    for comp, total in comp_hist.most_common(10):
        row = [str(cross.get((r, comp), 0)) for r in reasons_sorted]
        lines.append(f"| {comp} | " + " | ".join(row) + f" | {total} |")
    lines += [
        "",
        "### Sample E_BALL_ACCOUNTING diagnoses",
        "",
        *(f"- `{q['match_id']}`: {q['detail'][:160]}" for q in ball_acc),
        "",
        "## (3) Outcome alphabet (frozen) with train frequencies",
        "",
        "| class | train rows | train freq |",
        "|---|---|---|",
        *(f"| {r['outcome_class']} | {r['len']} | {r['freq']:.6f} |" for r in alpha.to_dicts()),
        "",
        f"K = {alpha.height} classes; train rows = {train.height}.",
        "",
        "## (4) Temporal split",
        "",
        "| split | matches | deliveries | start_date range |",
        "|---|---|---|---|",
    ]
    dmap = {d["temporal_split"]: d["len"] for d in split_counts}
    mmap = {d["temporal_split"]: d["len"] for d in match_counts}
    bmap = {b["temporal_split"]: (b["min"], b["max"]) for b in bounds}
    for s in ("train", "val", "test"):
        lo, hi = bmap[s]
        lines.append(f"| {s} | {mmap[s]} | {dmap[s]} | {lo} → {hi} |")
    lines += [
        "",
        "## (5) deliveries.parquet columns",
        "",
        "| column | dtype |",
        "|---|---|",
        *(f"| {name} | {dtype} |" for name, dtype in deliveries.schema.items()),
        "",
        f"{len(deliveries.columns)} columns x {deliveries.height} rows.",
        "",
        "## (6) CI",
        "",
        "Remote: `github.com/dudailia/cricstate` (private). First cloud run on `main`",
        "(commit `07a52ca`, the M1.1 patch): **green** — lint, type-check (mypy",
        "--strict), and the non-corpus test suite all passed.",
        "",
        "Run link: https://github.com/dudailia/cricstate/actions/runs/28619632017",
    ]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
